const EDIT_PAGE = "EDIT_PAGE"
const SAVE_PAGE_REQUEST = "SAVE_PAGE_REQUEST"
const SAVE_PAGE_SUCCESS = "SAVE_PAGE_SUCCESS"
const SAVE_PAGE_FAILURE = "SAVE_PAGE_FAILURE"
const FETCH_PAGE_REQUEST = "FETCH_PAGE_REQUEST"
const FETCH_PAGE_SUCCESS = "FETCH_PAGE_SUCCESS"
const FETCH_PAGE_FAILURE = "FETCH_PAGE_FAILURE"

const FETCH_DOWNLOAD_TABS_REQUEST = "FETCH_DOWNLOAD_TABS_REQUEST"
const FETCH_DOWNLOAD_TABS_SUCCESS = "FETCH_DOWNLOAD_TABS_SUCCESS"
const FETCH_DOWNLOAD_TABS_FAILURE = "FETCH_DOWNLOAD_TABS_FAILURE"
const FETCH_DOWNLOAD_CONTENT_REQUEST = "FETCH_DOWNLOAD_CONTENT_REQUEST"
const FETCH_DOWNLOAD_CONTENT_SUCCESS = "FETCH_DOWNLOAD_CONTENT_SUCCESS"
const FETCH_DOWNLOAD_CONTENT_FAILURE = "FETCH_DOWNLOAD_CONTENT_FAILURE"
const CHANGE_TAB = "CHANGE_TAB"

export {
  EDIT_PAGE,
  SAVE_PAGE_REQUEST,
  SAVE_PAGE_SUCCESS,
  SAVE_PAGE_FAILURE,
  FETCH_PAGE_FAILURE,
  FETCH_PAGE_REQUEST,
  FETCH_PAGE_SUCCESS,
  FETCH_DOWNLOAD_CONTENT_FAILURE,
  FETCH_DOWNLOAD_CONTENT_REQUEST,
  FETCH_DOWNLOAD_CONTENT_SUCCESS,
  FETCH_DOWNLOAD_TABS_FAILURE,
  FETCH_DOWNLOAD_TABS_REQUEST,
  FETCH_DOWNLOAD_TABS_SUCCESS,
  CHANGE_TAB,
}
