queue_rules:
  - name: default
    conditions:
      - check-success=Unit tests
      - check-success=codecov/patch
      - check-success=codecov/project

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=develop
      - check-success=Unit tests
      - check-success=codecov/patch
      - check-success=codecov/project
    actions:
      queue:
        name: default
        method: rebase