// flow-typed signature: 5b749167ec8e2d8ac40c2d8e3b98cbf0
// flow-typed version: <<STUB>>/dicty-components-navbar_v0.1.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dicty-components-navbar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dicty-components-navbar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dicty-components-navbar/examples/App' {
  declare module.exports: any;
}

declare module 'dicty-components-navbar/examples/webpack.config' {
  declare module.exports: any;
}

declare module 'dicty-components-navbar/flow-typed/polished' {
  declare module.exports: any;
}

declare module 'dicty-components-navbar/flow-typed/styled-components' {
  declare module.exports: any;
}

declare module 'dicty-components-navbar/lib/Components/Brand' {
  declare module.exports: any;
}

declare module 'dicty-components-navbar/lib/Components/Dropdown' {
  declare module.exports: any;
}

declare module 'dicty-components-navbar/lib/Components/Link' {
  declare module.exports: any;
}

declare module 'dicty-components-navbar/lib/Components/MenuIcon' {
  declare module.exports: any;
}

declare module 'dicty-components-navbar/lib/Components/Navbar' {
  declare module.exports: any;
}

declare module 'dicty-components-navbar/lib/index' {
  declare module.exports: any;
}

declare module 'dicty-components-navbar/lib/utils/darkenOrLighten' {
  declare module.exports: any;
}

declare module 'dicty-components-navbar/lib/utils/dom' {
  declare module.exports: any;
}

declare module 'dicty-components-navbar/src/__tests__/Brand.spec' {
  declare module.exports: any;
}

declare module 'dicty-components-navbar/src/__tests__/Dropdown.spec' {
  declare module.exports: any;
}

declare module 'dicty-components-navbar/src/__tests__/Link.spec' {
  declare module.exports: any;
}

declare module 'dicty-components-navbar/src/__tests__/MenuIcon.spec' {
  declare module.exports: any;
}

declare module 'dicty-components-navbar/src/__tests__/Navbar.spec' {
  declare module.exports: any;
}

declare module 'dicty-components-navbar/src/Components/Brand' {
  declare module.exports: any;
}

declare module 'dicty-components-navbar/src/Components/Dropdown' {
  declare module.exports: any;
}

declare module 'dicty-components-navbar/src/Components/Link' {
  declare module.exports: any;
}

declare module 'dicty-components-navbar/src/Components/MenuIcon' {
  declare module.exports: any;
}

declare module 'dicty-components-navbar/src/Components/Navbar' {
  declare module.exports: any;
}

declare module 'dicty-components-navbar/src/index' {
  declare module.exports: any;
}

declare module 'dicty-components-navbar/src/utils/darkenOrLighten' {
  declare module.exports: any;
}

declare module 'dicty-components-navbar/src/utils/dom' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dicty-components-navbar/examples/App.js' {
  declare module.exports: $Exports<'dicty-components-navbar/examples/App'>;
}
declare module 'dicty-components-navbar/examples/webpack.config.js' {
  declare module.exports: $Exports<'dicty-components-navbar/examples/webpack.config'>;
}
declare module 'dicty-components-navbar/flow-typed/polished.js' {
  declare module.exports: $Exports<'dicty-components-navbar/flow-typed/polished'>;
}
declare module 'dicty-components-navbar/flow-typed/styled-components.js' {
  declare module.exports: $Exports<'dicty-components-navbar/flow-typed/styled-components'>;
}
declare module 'dicty-components-navbar/lib/Components/Brand.js' {
  declare module.exports: $Exports<'dicty-components-navbar/lib/Components/Brand'>;
}
declare module 'dicty-components-navbar/lib/Components/Dropdown.js' {
  declare module.exports: $Exports<'dicty-components-navbar/lib/Components/Dropdown'>;
}
declare module 'dicty-components-navbar/lib/Components/Link.js' {
  declare module.exports: $Exports<'dicty-components-navbar/lib/Components/Link'>;
}
declare module 'dicty-components-navbar/lib/Components/MenuIcon.js' {
  declare module.exports: $Exports<'dicty-components-navbar/lib/Components/MenuIcon'>;
}
declare module 'dicty-components-navbar/lib/Components/Navbar.js' {
  declare module.exports: $Exports<'dicty-components-navbar/lib/Components/Navbar'>;
}
declare module 'dicty-components-navbar/lib/index.js' {
  declare module.exports: $Exports<'dicty-components-navbar/lib/index'>;
}
declare module 'dicty-components-navbar/lib/utils/darkenOrLighten.js' {
  declare module.exports: $Exports<'dicty-components-navbar/lib/utils/darkenOrLighten'>;
}
declare module 'dicty-components-navbar/lib/utils/dom.js' {
  declare module.exports: $Exports<'dicty-components-navbar/lib/utils/dom'>;
}
declare module 'dicty-components-navbar/src/__tests__/Brand.spec.js' {
  declare module.exports: $Exports<'dicty-components-navbar/src/__tests__/Brand.spec'>;
}
declare module 'dicty-components-navbar/src/__tests__/Dropdown.spec.js' {
  declare module.exports: $Exports<'dicty-components-navbar/src/__tests__/Dropdown.spec'>;
}
declare module 'dicty-components-navbar/src/__tests__/Link.spec.js' {
  declare module.exports: $Exports<'dicty-components-navbar/src/__tests__/Link.spec'>;
}
declare module 'dicty-components-navbar/src/__tests__/MenuIcon.spec.js' {
  declare module.exports: $Exports<'dicty-components-navbar/src/__tests__/MenuIcon.spec'>;
}
declare module 'dicty-components-navbar/src/__tests__/Navbar.spec.js' {
  declare module.exports: $Exports<'dicty-components-navbar/src/__tests__/Navbar.spec'>;
}
declare module 'dicty-components-navbar/src/Components/Brand.js' {
  declare module.exports: $Exports<'dicty-components-navbar/src/Components/Brand'>;
}
declare module 'dicty-components-navbar/src/Components/Dropdown.js' {
  declare module.exports: $Exports<'dicty-components-navbar/src/Components/Dropdown'>;
}
declare module 'dicty-components-navbar/src/Components/Link.js' {
  declare module.exports: $Exports<'dicty-components-navbar/src/Components/Link'>;
}
declare module 'dicty-components-navbar/src/Components/MenuIcon.js' {
  declare module.exports: $Exports<'dicty-components-navbar/src/Components/MenuIcon'>;
}
declare module 'dicty-components-navbar/src/Components/Navbar.js' {
  declare module.exports: $Exports<'dicty-components-navbar/src/Components/Navbar'>;
}
declare module 'dicty-components-navbar/src/index.js' {
  declare module.exports: $Exports<'dicty-components-navbar/src/index'>;
}
declare module 'dicty-components-navbar/src/utils/darkenOrLighten.js' {
  declare module.exports: $Exports<'dicty-components-navbar/src/utils/darkenOrLighten'>;
}
declare module 'dicty-components-navbar/src/utils/dom.js' {
  declare module.exports: $Exports<'dicty-components-navbar/src/utils/dom'>;
}
