// flow-typed signature: e5b302f81d942d04da9fec2e06a4ddf9
// flow-typed version: <<STUB>>/dicty-components-header-footer_v4.2.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dicty-components-header-footer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dicty-components-header-footer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dicty-components-header-footer/es/components/Footer' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/es/components/Footer.test' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/es/components/Header' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/es/components/Header.test' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/es/data/footer' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/es/data/header' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/es/index' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/es/styles/footer/FooterContainer' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/es/styles/footer/FooterItem' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/es/styles/footer/FooterItemsContainer' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/es/styles/footer/FooterItemsHeader' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/es/styles/footer/FooterLink' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/es/styles/header/Container' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/es/styles/header/Img' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/es/styles/header/index' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/es/styles/header/Link' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/es/styles/header/LinksContainer' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/es/styles/header/Logo' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/es/styles/header/Magnifier' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/es/styles/header/Right' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/es/styles/header/SearchBar' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/es/styles/header/SearchContainer' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/lib/components/Footer' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/lib/components/Footer.test' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/lib/components/Header' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/lib/components/Header.test' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/lib/data/footer' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/lib/data/header' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/lib/index' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/lib/styles/footer/FooterContainer' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/lib/styles/footer/FooterItem' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/lib/styles/footer/FooterItemsContainer' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/lib/styles/footer/FooterItemsHeader' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/lib/styles/footer/FooterLink' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/lib/styles/header/Container' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/lib/styles/header/Img' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/lib/styles/header/index' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/lib/styles/header/Link' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/lib/styles/header/LinksContainer' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/lib/styles/header/Logo' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/lib/styles/header/Magnifier' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/lib/styles/header/Right' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/lib/styles/header/SearchBar' {
  declare module.exports: any;
}

declare module 'dicty-components-header-footer/lib/styles/header/SearchContainer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dicty-components-header-footer/es/components/Footer.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/es/components/Footer'>;
}
declare module 'dicty-components-header-footer/es/components/Footer.test.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/es/components/Footer.test'>;
}
declare module 'dicty-components-header-footer/es/components/Header.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/es/components/Header'>;
}
declare module 'dicty-components-header-footer/es/components/Header.test.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/es/components/Header.test'>;
}
declare module 'dicty-components-header-footer/es/data/footer.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/es/data/footer'>;
}
declare module 'dicty-components-header-footer/es/data/header.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/es/data/header'>;
}
declare module 'dicty-components-header-footer/es/index.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/es/index'>;
}
declare module 'dicty-components-header-footer/es/styles/footer/FooterContainer.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/es/styles/footer/FooterContainer'>;
}
declare module 'dicty-components-header-footer/es/styles/footer/FooterItem.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/es/styles/footer/FooterItem'>;
}
declare module 'dicty-components-header-footer/es/styles/footer/FooterItemsContainer.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/es/styles/footer/FooterItemsContainer'>;
}
declare module 'dicty-components-header-footer/es/styles/footer/FooterItemsHeader.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/es/styles/footer/FooterItemsHeader'>;
}
declare module 'dicty-components-header-footer/es/styles/footer/FooterLink.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/es/styles/footer/FooterLink'>;
}
declare module 'dicty-components-header-footer/es/styles/header/Container.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/es/styles/header/Container'>;
}
declare module 'dicty-components-header-footer/es/styles/header/Img.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/es/styles/header/Img'>;
}
declare module 'dicty-components-header-footer/es/styles/header/index.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/es/styles/header/index'>;
}
declare module 'dicty-components-header-footer/es/styles/header/Link.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/es/styles/header/Link'>;
}
declare module 'dicty-components-header-footer/es/styles/header/LinksContainer.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/es/styles/header/LinksContainer'>;
}
declare module 'dicty-components-header-footer/es/styles/header/Logo.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/es/styles/header/Logo'>;
}
declare module 'dicty-components-header-footer/es/styles/header/Magnifier.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/es/styles/header/Magnifier'>;
}
declare module 'dicty-components-header-footer/es/styles/header/Right.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/es/styles/header/Right'>;
}
declare module 'dicty-components-header-footer/es/styles/header/SearchBar.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/es/styles/header/SearchBar'>;
}
declare module 'dicty-components-header-footer/es/styles/header/SearchContainer.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/es/styles/header/SearchContainer'>;
}
declare module 'dicty-components-header-footer/lib/components/Footer.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/lib/components/Footer'>;
}
declare module 'dicty-components-header-footer/lib/components/Footer.test.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/lib/components/Footer.test'>;
}
declare module 'dicty-components-header-footer/lib/components/Header.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/lib/components/Header'>;
}
declare module 'dicty-components-header-footer/lib/components/Header.test.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/lib/components/Header.test'>;
}
declare module 'dicty-components-header-footer/lib/data/footer.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/lib/data/footer'>;
}
declare module 'dicty-components-header-footer/lib/data/header.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/lib/data/header'>;
}
declare module 'dicty-components-header-footer/lib/index.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/lib/index'>;
}
declare module 'dicty-components-header-footer/lib/styles/footer/FooterContainer.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/lib/styles/footer/FooterContainer'>;
}
declare module 'dicty-components-header-footer/lib/styles/footer/FooterItem.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/lib/styles/footer/FooterItem'>;
}
declare module 'dicty-components-header-footer/lib/styles/footer/FooterItemsContainer.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/lib/styles/footer/FooterItemsContainer'>;
}
declare module 'dicty-components-header-footer/lib/styles/footer/FooterItemsHeader.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/lib/styles/footer/FooterItemsHeader'>;
}
declare module 'dicty-components-header-footer/lib/styles/footer/FooterLink.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/lib/styles/footer/FooterLink'>;
}
declare module 'dicty-components-header-footer/lib/styles/header/Container.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/lib/styles/header/Container'>;
}
declare module 'dicty-components-header-footer/lib/styles/header/Img.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/lib/styles/header/Img'>;
}
declare module 'dicty-components-header-footer/lib/styles/header/index.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/lib/styles/header/index'>;
}
declare module 'dicty-components-header-footer/lib/styles/header/Link.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/lib/styles/header/Link'>;
}
declare module 'dicty-components-header-footer/lib/styles/header/LinksContainer.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/lib/styles/header/LinksContainer'>;
}
declare module 'dicty-components-header-footer/lib/styles/header/Logo.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/lib/styles/header/Logo'>;
}
declare module 'dicty-components-header-footer/lib/styles/header/Magnifier.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/lib/styles/header/Magnifier'>;
}
declare module 'dicty-components-header-footer/lib/styles/header/Right.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/lib/styles/header/Right'>;
}
declare module 'dicty-components-header-footer/lib/styles/header/SearchBar.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/lib/styles/header/SearchBar'>;
}
declare module 'dicty-components-header-footer/lib/styles/header/SearchContainer.js' {
  declare module.exports: $Exports<'dicty-components-header-footer/lib/styles/header/SearchContainer'>;
}
