// flow-typed signature: eca634330a044ef79c0142c2891ccbb5
// flow-typed version: <<STUB>>/dicty-components-page-editor_v1.0.0/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dicty-components-page-editor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dicty-components-page-editor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dicty-components-page-editor/dist/index.es' {
  declare module.exports: any;
}

declare module 'dicty-components-page-editor/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dicty-components-page-editor/dist/index.es.js' {
  declare module.exports: $Exports<'dicty-components-page-editor/dist/index.es'>;
}
declare module 'dicty-components-page-editor/dist/index' {
  declare module.exports: $Exports<'dicty-components-page-editor/dist'>;
}
declare module 'dicty-components-page-editor/dist/index.js' {
  declare module.exports: $Exports<'dicty-components-page-editor/dist'>;
}
