// flow-typed signature: c7b0f9b932fcca95435eb06cf127422c
// flow-typed version: <<STUB>>/font-awesome_v4.7/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'font-awesome'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'font-awesome' {
  declare module.exports: any;
}
