// flow-typed signature: 9a33e40b52f34283ca885f5caf53cf0a
// flow-typed version: <<STUB>>/react-responsive-carousel_v3.1.41/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-responsive-carousel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-responsive-carousel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-responsive-carousel/lib/components/Carousel' {
  declare module.exports: any;
}

declare module 'react-responsive-carousel/lib/components/Thumbs' {
  declare module.exports: any;
}

declare module 'react-responsive-carousel/lib/cssClasses' {
  declare module.exports: any;
}

declare module 'react-responsive-carousel/lib/CSSTranslate' {
  declare module.exports: any;
}

declare module 'react-responsive-carousel/lib/customPropTypes' {
  declare module.exports: any;
}

declare module 'react-responsive-carousel/lib/dimensions' {
  declare module.exports: any;
}

declare module 'react-responsive-carousel/lib/has3d' {
  declare module.exports: any;
}

declare module 'react-responsive-carousel/lib/index' {
  declare module.exports: any;
}

declare module 'react-responsive-carousel/lib/object-assign' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-responsive-carousel/lib/components/Carousel.js' {
  declare module.exports: $Exports<'react-responsive-carousel/lib/components/Carousel'>;
}
declare module 'react-responsive-carousel/lib/components/Thumbs.js' {
  declare module.exports: $Exports<'react-responsive-carousel/lib/components/Thumbs'>;
}
declare module 'react-responsive-carousel/lib/cssClasses.js' {
  declare module.exports: $Exports<'react-responsive-carousel/lib/cssClasses'>;
}
declare module 'react-responsive-carousel/lib/CSSTranslate.js' {
  declare module.exports: $Exports<'react-responsive-carousel/lib/CSSTranslate'>;
}
declare module 'react-responsive-carousel/lib/customPropTypes.js' {
  declare module.exports: $Exports<'react-responsive-carousel/lib/customPropTypes'>;
}
declare module 'react-responsive-carousel/lib/dimensions.js' {
  declare module.exports: $Exports<'react-responsive-carousel/lib/dimensions'>;
}
declare module 'react-responsive-carousel/lib/has3d.js' {
  declare module.exports: $Exports<'react-responsive-carousel/lib/has3d'>;
}
declare module 'react-responsive-carousel/lib/index.js' {
  declare module.exports: $Exports<'react-responsive-carousel/lib/index'>;
}
declare module 'react-responsive-carousel/lib/object-assign.js' {
  declare module.exports: $Exports<'react-responsive-carousel/lib/object-assign'>;
}
