// flow-typed signature: 2f901bbce6ff6e83fc86741e4384c406
// flow-typed version: <<STUB>>/slate-edit-table_v0.16.2/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slate-edit-table'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'slate-edit-table' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slate-edit-table/dist/changes/clearCell' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/changes/index' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/changes/insertColumn' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/changes/insertRow' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/changes/insertTable' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/changes/moveSelection' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/changes/moveSelectionBy' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/changes/removeColumn' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/changes/removeColumnByKey' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/changes/removeRow' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/changes/removeRowByKey' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/changes/removeTable' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/changes/removeTableByKey' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/core' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/handlers/index' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/handlers/onBackspace' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/handlers/onEnter' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/handlers/onKeyDown' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/handlers/onModEnter' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/handlers/onTab' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/handlers/onUpDown' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/index' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/options' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/utils/createCell' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/utils/createRow' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/utils/createTable' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/utils/forEachCells' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/utils/getCellsAtColumn' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/utils/getCellsAtRow' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/utils/getPosition' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/utils/getRow' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/utils/index' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/utils/isSelectionInTable' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/utils/isSelectionOutOfTable' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/utils/TablePosition' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/validation/index' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/validation/schema' {
  declare module.exports: any;
}

declare module 'slate-edit-table/dist/validation/validateNode' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slate-edit-table/dist/changes/clearCell.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/changes/clearCell'>;
}
declare module 'slate-edit-table/dist/changes/index.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/changes/index'>;
}
declare module 'slate-edit-table/dist/changes/insertColumn.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/changes/insertColumn'>;
}
declare module 'slate-edit-table/dist/changes/insertRow.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/changes/insertRow'>;
}
declare module 'slate-edit-table/dist/changes/insertTable.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/changes/insertTable'>;
}
declare module 'slate-edit-table/dist/changes/moveSelection.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/changes/moveSelection'>;
}
declare module 'slate-edit-table/dist/changes/moveSelectionBy.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/changes/moveSelectionBy'>;
}
declare module 'slate-edit-table/dist/changes/removeColumn.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/changes/removeColumn'>;
}
declare module 'slate-edit-table/dist/changes/removeColumnByKey.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/changes/removeColumnByKey'>;
}
declare module 'slate-edit-table/dist/changes/removeRow.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/changes/removeRow'>;
}
declare module 'slate-edit-table/dist/changes/removeRowByKey.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/changes/removeRowByKey'>;
}
declare module 'slate-edit-table/dist/changes/removeTable.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/changes/removeTable'>;
}
declare module 'slate-edit-table/dist/changes/removeTableByKey.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/changes/removeTableByKey'>;
}
declare module 'slate-edit-table/dist/core.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/core'>;
}
declare module 'slate-edit-table/dist/handlers/index.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/handlers/index'>;
}
declare module 'slate-edit-table/dist/handlers/onBackspace.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/handlers/onBackspace'>;
}
declare module 'slate-edit-table/dist/handlers/onEnter.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/handlers/onEnter'>;
}
declare module 'slate-edit-table/dist/handlers/onKeyDown.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/handlers/onKeyDown'>;
}
declare module 'slate-edit-table/dist/handlers/onModEnter.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/handlers/onModEnter'>;
}
declare module 'slate-edit-table/dist/handlers/onTab.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/handlers/onTab'>;
}
declare module 'slate-edit-table/dist/handlers/onUpDown.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/handlers/onUpDown'>;
}
declare module 'slate-edit-table/dist/index.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/index'>;
}
declare module 'slate-edit-table/dist/options.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/options'>;
}
declare module 'slate-edit-table/dist/utils/createCell.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/utils/createCell'>;
}
declare module 'slate-edit-table/dist/utils/createRow.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/utils/createRow'>;
}
declare module 'slate-edit-table/dist/utils/createTable.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/utils/createTable'>;
}
declare module 'slate-edit-table/dist/utils/forEachCells.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/utils/forEachCells'>;
}
declare module 'slate-edit-table/dist/utils/getCellsAtColumn.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/utils/getCellsAtColumn'>;
}
declare module 'slate-edit-table/dist/utils/getCellsAtRow.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/utils/getCellsAtRow'>;
}
declare module 'slate-edit-table/dist/utils/getPosition.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/utils/getPosition'>;
}
declare module 'slate-edit-table/dist/utils/getRow.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/utils/getRow'>;
}
declare module 'slate-edit-table/dist/utils/index.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/utils/index'>;
}
declare module 'slate-edit-table/dist/utils/isSelectionInTable.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/utils/isSelectionInTable'>;
}
declare module 'slate-edit-table/dist/utils/isSelectionOutOfTable.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/utils/isSelectionOutOfTable'>;
}
declare module 'slate-edit-table/dist/utils/TablePosition.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/utils/TablePosition'>;
}
declare module 'slate-edit-table/dist/validation/index.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/validation/index'>;
}
declare module 'slate-edit-table/dist/validation/schema.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/validation/schema'>;
}
declare module 'slate-edit-table/dist/validation/validateNode.js' {
  declare module.exports: $Exports<'slate-edit-table/dist/validation/validateNode'>;
}
