// flow-typed signature: ee1bd63ce5a59a8107b4eb116ded22a2
// flow-typed version: <<STUB>>/slate-edit-list_vx.x.x/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slate-edit-list'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'slate-edit-list' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slate-edit-list/dist/changes/decreaseItemDepth' {
  declare module.exports: any;
}

declare module 'slate-edit-list/dist/changes/increaseItemDepth' {
  declare module.exports: any;
}

declare module 'slate-edit-list/dist/changes/index' {
  declare module.exports: any;
}

declare module 'slate-edit-list/dist/changes/splitListItem' {
  declare module.exports: any;
}

declare module 'slate-edit-list/dist/changes/unwrapList' {
  declare module.exports: any;
}

declare module 'slate-edit-list/dist/changes/wrapInList' {
  declare module.exports: any;
}

declare module 'slate-edit-list/dist/core' {
  declare module.exports: any;
}

declare module 'slate-edit-list/dist/handlers/index' {
  declare module.exports: any;
}

declare module 'slate-edit-list/dist/handlers/onBackspace' {
  declare module.exports: any;
}

declare module 'slate-edit-list/dist/handlers/onEnter' {
  declare module.exports: any;
}

declare module 'slate-edit-list/dist/handlers/onTab' {
  declare module.exports: any;
}

declare module 'slate-edit-list/dist/index' {
  declare module.exports: any;
}

declare module 'slate-edit-list/dist/options' {
  declare module.exports: any;
}

declare module 'slate-edit-list/dist/utils/getCurrentItem' {
  declare module.exports: any;
}

declare module 'slate-edit-list/dist/utils/getCurrentList' {
  declare module.exports: any;
}

declare module 'slate-edit-list/dist/utils/getItemDepth' {
  declare module.exports: any;
}

declare module 'slate-edit-list/dist/utils/getItemsAtRange' {
  declare module.exports: any;
}

declare module 'slate-edit-list/dist/utils/getListForItem' {
  declare module.exports: any;
}

declare module 'slate-edit-list/dist/utils/getPreviousItem' {
  declare module.exports: any;
}

declare module 'slate-edit-list/dist/utils/index' {
  declare module.exports: any;
}

declare module 'slate-edit-list/dist/utils/isList' {
  declare module.exports: any;
}

declare module 'slate-edit-list/dist/utils/isSelectionInList' {
  declare module.exports: any;
}

declare module 'slate-edit-list/dist/validation/index' {
  declare module.exports: any;
}

declare module 'slate-edit-list/dist/validation/schema' {
  declare module.exports: any;
}

declare module 'slate-edit-list/dist/validation/validateNode' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slate-edit-list/dist/changes/decreaseItemDepth.js' {
  declare module.exports: $Exports<'slate-edit-list/dist/changes/decreaseItemDepth'>;
}
declare module 'slate-edit-list/dist/changes/increaseItemDepth.js' {
  declare module.exports: $Exports<'slate-edit-list/dist/changes/increaseItemDepth'>;
}
declare module 'slate-edit-list/dist/changes/index.js' {
  declare module.exports: $Exports<'slate-edit-list/dist/changes/index'>;
}
declare module 'slate-edit-list/dist/changes/splitListItem.js' {
  declare module.exports: $Exports<'slate-edit-list/dist/changes/splitListItem'>;
}
declare module 'slate-edit-list/dist/changes/unwrapList.js' {
  declare module.exports: $Exports<'slate-edit-list/dist/changes/unwrapList'>;
}
declare module 'slate-edit-list/dist/changes/wrapInList.js' {
  declare module.exports: $Exports<'slate-edit-list/dist/changes/wrapInList'>;
}
declare module 'slate-edit-list/dist/core.js' {
  declare module.exports: $Exports<'slate-edit-list/dist/core'>;
}
declare module 'slate-edit-list/dist/handlers/index.js' {
  declare module.exports: $Exports<'slate-edit-list/dist/handlers/index'>;
}
declare module 'slate-edit-list/dist/handlers/onBackspace.js' {
  declare module.exports: $Exports<'slate-edit-list/dist/handlers/onBackspace'>;
}
declare module 'slate-edit-list/dist/handlers/onEnter.js' {
  declare module.exports: $Exports<'slate-edit-list/dist/handlers/onEnter'>;
}
declare module 'slate-edit-list/dist/handlers/onTab.js' {
  declare module.exports: $Exports<'slate-edit-list/dist/handlers/onTab'>;
}
declare module 'slate-edit-list/dist/index.js' {
  declare module.exports: $Exports<'slate-edit-list/dist/index'>;
}
declare module 'slate-edit-list/dist/options.js' {
  declare module.exports: $Exports<'slate-edit-list/dist/options'>;
}
declare module 'slate-edit-list/dist/utils/getCurrentItem.js' {
  declare module.exports: $Exports<'slate-edit-list/dist/utils/getCurrentItem'>;
}
declare module 'slate-edit-list/dist/utils/getCurrentList.js' {
  declare module.exports: $Exports<'slate-edit-list/dist/utils/getCurrentList'>;
}
declare module 'slate-edit-list/dist/utils/getItemDepth.js' {
  declare module.exports: $Exports<'slate-edit-list/dist/utils/getItemDepth'>;
}
declare module 'slate-edit-list/dist/utils/getItemsAtRange.js' {
  declare module.exports: $Exports<'slate-edit-list/dist/utils/getItemsAtRange'>;
}
declare module 'slate-edit-list/dist/utils/getListForItem.js' {
  declare module.exports: $Exports<'slate-edit-list/dist/utils/getListForItem'>;
}
declare module 'slate-edit-list/dist/utils/getPreviousItem.js' {
  declare module.exports: $Exports<'slate-edit-list/dist/utils/getPreviousItem'>;
}
declare module 'slate-edit-list/dist/utils/index.js' {
  declare module.exports: $Exports<'slate-edit-list/dist/utils/index'>;
}
declare module 'slate-edit-list/dist/utils/isList.js' {
  declare module.exports: $Exports<'slate-edit-list/dist/utils/isList'>;
}
declare module 'slate-edit-list/dist/utils/isSelectionInList.js' {
  declare module.exports: $Exports<'slate-edit-list/dist/utils/isSelectionInList'>;
}
declare module 'slate-edit-list/dist/validation/index.js' {
  declare module.exports: $Exports<'slate-edit-list/dist/validation/index'>;
}
declare module 'slate-edit-list/dist/validation/schema.js' {
  declare module.exports: $Exports<'slate-edit-list/dist/validation/schema'>;
}
declare module 'slate-edit-list/dist/validation/validateNode.js' {
  declare module.exports: $Exports<'slate-edit-list/dist/validation/validateNode'>;
}
