// flow-typed signature: 4afcb12d894a9519c095aa651235dc76
// flow-typed version: <<STUB>>/twitter-fetcher_vx.x.x/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'twitter-fetcher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'twitter-fetcher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'twitter-fetcher/js/exampleUsage' {
  declare module.exports: any;
}

declare module 'twitter-fetcher/js/twitterFetcher_min' {
  declare module.exports: any;
}

declare module 'twitter-fetcher/js/twitterFetcher' {
  declare module.exports: any;
}

// Filename aliases
declare module 'twitter-fetcher/js/exampleUsage.js' {
  declare module.exports: $Exports<'twitter-fetcher/js/exampleUsage'>;
}
declare module 'twitter-fetcher/js/twitterFetcher_min.js' {
  declare module.exports: $Exports<'twitter-fetcher/js/twitterFetcher_min'>;
}
declare module 'twitter-fetcher/js/twitterFetcher.js' {
  declare module.exports: $Exports<'twitter-fetcher/js/twitterFetcher'>;
}
