import "core-js/features/symbol/iterator"
import "core-js/features/object/entries"
import "core-js/features/object/values"
import "core-js/features/array/find"
import "core-js/features/array/includes"
import "core-js/features/string/ends-with"
import "core-js/features/string/includes"
import "react-app-polyfill/ie11"
