name: TSC
on: pull_request
jobs:
  tsc:
    runs-on: ubuntu-18.04
    steps:
      - name: set up node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: check out code
        uses: actions/checkout@v2
      - name: yarn install
        run: yarn install
      - name: tsc
        run: |
          mv src/common/utils/clientConfig.sample.ts src/common/utils/clientConfig.ts
          yarn run tsc
